### ISSUE TITLE
Tuning Up The Mod

### ISSUE THREAD

**Issue by sbmmsux** [EnderBoy9217/Grunt-Mode#13]
Hello there, you'll see.. I use this and the "Grunt Mode 1" mods in order to play some private PvE matches.. what you guys have made here is the closest thing we have to a Bots mode on Titanfall, and I mean a real Bots mode.. with Pilots, Titans and everything..

What I wanted to ask ya is.. which file contains the parameter that determines when the Pilots, Reapers, Titans and etc start spawing on the match? I wanted to change the parameter so all of those NPC's showed up quicker.. I managed to made that change on the DBmaoha mod easily but.. couldnt find the option in your mod.

I like the class system you made, btw.. Also, I wanted to know.. is there a way to use that mod of yours on any other game mode besides of Attrition? Thanks..

**Comment by dbyale** [comment]
Sorry for the late repsonse, the values are stored near the top of the
gamemode_aitdm file, it will be moved to be a mod.json convar soon

**Comment by sbmmsux** [comment]
Nah, it's cool.. aint worry.. thx for the info.. Btw.. is there a way to implement ur mod on other game modes besides Attrition? Idk, maybe in Frontier War or some, just curious..

**Comment by dbyale** [comment]
I have been thinking about adding it to amped hard points, I’ll likely do
that when the mod if “finished” so I don’t have to constantly repeat changes

**Comment by sbmmsux** [comment]
nice.. but.. how's that "hardpoint" mode in titanfall? i know it only because of cod jejeje.. and pretty sure it's not the same.. i mean, this hardpoint from titanfall would be pilots only? or it involves titans too?

**Comment by sbmmsux** [comment]
another question.. is there a possibility to make the pilot class in ur mod can request titans? u know, the energy bar on bottom left  of the screen indicating if u can request a titan or not.. i played a match recently and when i could respawn as a pilot.. didnt see that bar..

**Comment by dbyale** [comment]
Amped hard point is a gamemode on vanilla Titanfall that surprisingly few
people play on Northstar.

Essentially it’s like COD domination, but after you capture a hard point,
you can stay to defend it to get double the points from that hard point.

**Comment by dbyale** [comment]
The gamemode disables the titan/boost bar entirely, if you still want to
have titans, I can send you a version with edits that allow it.

However, grunt classes would also be able to spawn titans, and entering a
titan with specific classes such as spectres will likely lead to a crash.

**Comment by sbmmsux** [comment]
ouch! yeah.. we better leave it as it is jejeje.. thanks for ur response.. looking forward to play that "hardpoint" mode too.. i mean, attrition is cool but.. sometimes u just wanna play something else..
